### ISSUE TITLE
Clearning out README into Small & moving remaining documentation to wiki

### ISSUE THREAD

**Issue by ananthulasrikar** [WiproOpenSourcePractice/openbdre#13]
I think we need to move README to Wiki for clear  documentation of this project . Comments and suggestions are welcome.

**Comment by wiprodev** [comment]
README is the landing page of the project and it should have enough information for some one to quickly understand what BDRE has and can do. If it grows off limit then we need to have hyperlinks and move the documents to linked pages. We are considering registering a website where we could maintain those structure.

From: Srikar
Reply-To: WiproOpenSourcePractice/openbdre
Date: Tuesday, January 26, 2016 at 12:46 PM
To: WiproOpenSourcePractice/openbdre
Subject: [openbdre] Clearning out README into Small & moving remaining documentation to wiki (#13)


I think we need to move README to Wiki for clear documentation of this project . Comments and suggestions are welcome.

—
Reply to this email directly or view it on GitHub<https://github.com/WiproOpenSourcePractice/openbdre/issues/13>.

The information contained in this electronic message and any attachments to this message are intended for the exclusive use of the addressee(s) and may contain proprietary, confidential or privileged information. If you are not the intended recipient, you should not disseminate, distribute or copy this e-mail. Please notify the sender immediately and destroy all copies of this message and any attachments. WARNING: Computer viruses can be transmitted via email. The recipient should check this email and any attachments for the presence of viruses. The company accepts no liability for any damage caused by any virus transmitted by this email. www.wipro.com

**Comment by sudheesh001** [comment]
@wiprodev @ananthulasrikar So I've just started to clone and set this project up but I feel it'd have been nicer if the project's documentation was split into multiple smaller files and the main `READMe.md` linking them to the required files.

One clear thing to do would be to move [Contributing](https://github.com/WiproOpenSourcePractice/openbdre#how-to-contribute) to a new file called `CONTRIBUTING.md` and let this contain the best practices of reviewing pull requests and changes.

If you think this is great, I'd love to make the changes.

**Comment by wiprodev** [comment]
Yes. We plan to do it. We are currently using github pages which automatically creates project sites index.html from the md file. So the limitation is it's currently supports only one page. Another option is to use jekyll. Could you check this out and let us know if we can use this? https://help.github.com/articles/using-jekyll-with-pages/ ? Also please join bdre@googlegroups.com (it's public) and sign up in BDRE Jira https://openbdre.atlassian.net/ and create a story so you can start working on that.

**Comment by wiprodev** [comment]
@sudheesh001 please migrate this issue to Jira.
